### ISSUE TITLE
Solving query issues

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/QueryLibrary#1]
@MaximMoinat We have run all the queries automatically to check if the run and how long they take.

The results are in the google sheet that has been send to you.

Would you be able to help with fixing queries? Most syntax errors are related to CDM updates or missing aliases on subqueries I think.

**Comment by MaximMoinat** [comment]
Yes of course, and I might ask for some help within The Hyve.

On which CDM version have you run the queries? And did you use SqlRender? (although for Sql Server it should not matter of course)

**Comment by PRijnbeek** [comment]
I think this is 5.2.2 from http://www.ltscomputingllc.com/downloads/ but not 100% sure since the CDM version is not stored in the tables... 

We loaded it on Azure Sql Server but I think we also tested on our PostgreSQL data base and tried the test servers of Martijn (these are too slow) that has 'all' dialects.

**Comment by PRijnbeek** [comment]
See this new code that may help you:

https://github.com/EHDEN/QueryLibrary/blob/master/extras/Test.R

**Comment by PRijnbeek** [comment]
@MaximMoinat can we move this forward a bit next week? have a quick chat about this over Skype on Monday?

**Comment by MaximMoinat** [comment]
Thanks for the chat today :). One practical issue: do you want us to commit directly to this repo, or fork it and make pull requests? The first is more efficient for these small, incremental changes. If you agree, can you make us (me and @tropicalberto) collaborators?

**Comment by PRijnbeek** [comment]
Sure, you are collaborators now with write permissions. For me it is fine to work in Master together now, or we can make a branch each that is also possible. Let me know what you prefer.

**Comment by PRijnbeek** [comment]
Guys the link above to the Excel is now to a shared version on Google drive we could sign off queries on.

**Comment by MaximMoinat** [comment]
Care site and Condition queries are updated. The tests still pass on our Postgres database.

The following main cleaning steps performed:
* Made joins explicit (i.e. do not name multiple tables in FROM clause)
* Removed any v4 specific logic. e.g. removed select of `concept.vocabulary_name`, as the vocabulary_id's in V5+ are already descriptive
* Replaced `BETWEEN valid_start_date AND valid_end_date` by this check `invalid_reason IS NULL` (see also [this issue](https://github.com/OHDSI/QueryLibrary/issues/6))

Side note: one query ([CS02](https://github.com/EHDEN/QueryLibrary/blob/master/inst/shinyApps/QueryLibrary/queries/care_site/CS02.md)) passed the test while not all tables were prefixed with `@cdm`. It probably passed because the default schema of the test database was the cdm schema. Something to be aware of.

**Comment by tropicalberto** [comment]
Hi all,  the condition_occurrence queries have been updated as well. I have added a few queries that were missing in the repository

Edit: all the updated observation_period queries are also available in the repository
