### ISSUE TITLE
General approach to tackle queries that use regular expressions

### ISSUE THREAD

**Issue by tropicalberto** [EHDEN/QueryLibrary#7]
Hi all, 

I noticed that there are some queries that use regular expressions. Some examples are **D02** (https://github.com/EHDEN/QueryLibrary/blob/master/inst/shinyApps/QueryLibrary/queries/drug/D02_Find_drug_or_class_by_keyword.md) **P02** (https://github.com/EHDEN/QueryLibrary/blob/master/inst/shinyApps/QueryLibrary/queries/procedure/P02_Find_a_procedure_from_a_keyword.md) or **O01** (https://github.com/EHDEN/QueryLibrary/blob/master/inst/shinyApps/QueryLibrary/queries/observation/O01_Find_a_Observation_from_a_keyword.md).

In the replacement rules from the Sqlrender package (https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv) there is not any pattern that could be used to define "sql-agnostic" regular expression rules.

I tested the latest commit to the **D02** query and it doesn't work in our Postgres instance (it uses the patindex function which is specific to SQL server). 

Would it be wise to raise this issue to the Sqlrender community before proceeding to modify the queries that make use of approaches based on regular expressions? (or is there any sql-agnostic way to follow this approach? I'm not an experienced user of regular expressions in SQL).

**Comment by bmosseveld** [comment]
Hi Alberto,

We didn't test it on a Postgres database yet but I can imagine that the Sqlrenderer cannot handle it.
For simple pattern matching like the examples in the queries you can use LIKE. It won't be easy to handle more complex pattern matching because you not only need to replace the pattern matching function but probably also have to translate the regular expression from T-SQL dialect to the dialect of the specific database. And then you may also run in the problem that not all those dialects are equally powerful.
Maybe it is better to keep the pattern matching in these example queries simple, for example by using LIKE, and if you want more complex pattern matching you replace it yourself by the database specific pattern matching function before executing it. You have to edit it anyway to adjust it to your own needs.

**Comment by tropicalberto** [comment]
Hi Mees, thanks for you input, indeed that is a feasible option! For the requirements of those queries the LIKE statement did work, I have already tested it with the queries P02 and O02  and it works.

**Comment by PRijnbeek** [comment]
Agree let’s do this.
